### PR TITLE
added day1

### PR DESCRIPTION
**Pull request by SudiptaAChy**
successfully solved day1 task and has been added

### CODE REVIEW

**Comment by rahulsain3000** [comment]
please update readme file also we have updated the rules check at readme file

**Comment by rahulsain3000** [comment]
> please update readme file also we have updated the rules check at readme file

@SudiptaAChy Please make a column for dart and mark tick in readme file and

**Comment by SudiptaAChy** [comment]
> > please update readme file also we have updated the rules check at readme file
> 
> @SudiptaAChy Please make a column for dart and mark tick in readme file and

Hi i have updated

**Comment by rahulsain3000** [comment]
@SudiptaAChy Please make a PR again as there was some error on my side ,don't update readme file regarding day 1 to day 3

**Pull request merged**
