### PR TITLE
Solution to Day 28 on Hackerrank 30 Days of Code

### PR DESCRIPTION
**Pull request by raj1238**

### CODE REVIEW

**Comment by raj1238** [comment]
@rahulsain3000 Can you please approve my PR for Hactoberfest. The alternative PR which got merged was opened after mine. The same follows for my other PRs as well. Please look into it. And lastly, thanks for this amazing initiative. 30 Days of code is the first stepping stone for any beginner. :)

**Comment by rahulsain3000** [comment]
I will not merge this but approved this PR so it will be counted on your end

**Comment by raj1238** [comment]
Thanks, man :)  Please, have a look at this one as well: https://github.com/rahulsain3000/Hackerrank_30daysOFcode/pull/53

**Review by rahulsain3000 — APPROVED** [review]

**Comment by rahulsain3000** [comment]
@raj1238 If this, gone through review period please close all of your pending PR.

**Pull request closed without merging**
