### PR TITLE
HackerRank's Day0 Python and C solutions

### PR DESCRIPTION
**Pull request by alvinma**
I have solved HackerRank's Day0 problem in Python3 and C. This solution is passing 100% of the submission criteria.

### CODE REVIEW

**Comment by rahulsain3000** [comment]
It will be great if you solved all 30 day code in these language, and then make a pull request I will review it

**Comment by alvinma** [comment]
> It will be great if you solved all 30 day code in these language, and then make a pull request I will review it

Alright. I just don't have access to all 30 day code. It looks like I'll have them all unlocked in 30 days.

**Comment by rahulsain3000** [comment]
no , you could take help from [this](https://github.com/kalpak92/HackerRank-30-Days-of-Code) for python questions

**Comment by rahulsain3000** [comment]
If you're participating in #Hacktoberfest please mind that PR counts in the month of October. So please send a valid PR in Oct you can close this one.

Thank you

**Comment by alvinma** [comment]
Hi @rahulsain3000 ,

Thank you for the link! I just realized I could just search up the title of the problem to find it. hahaha..

I have a question though. Unless I am assigned all the Python ( or C, or C++) questions, wouldn't it be preferable that I create a PR for each problem to avoid any conflicts? We can bump it up to 5 questions per PR so you don't get bombarded with PRs.

My reasoning is for:
- **Avoiding Conflicts**: If 2 people are working on the same problems at the same time, one of those 2 will be wasting their time since the other person had already submitted in a PR.
- **Performance**: Even though all the solutions for the 30 problems are already out there, I would like to attempt the problems before I create a PR. I haven't taken a look at the 30 problems yet, but it might take some time. If you implement the 5 problems per PR structure, while I am working on my 5 problems, someone else can be working on another set of 5.

Thanks,
Alvin

**Pull request closed without merging**
