### PR TITLE
Day 25 PHP

### PR DESCRIPTION
**Pull request by VenkatVuddagiri**

### CODE REVIEW

**Review by rahulsain3000 — CHANGES_REQUESTED** [review]
Why you marking cross at readme file

**Review by rahulsain3000 — APPROVED** [review]

**Comment by VenkatVuddagiri** [comment]
I guess I've made a mistake in README file, that's why it didn't get rendered properly. Sorry for my mistake.
Shall I raise an issue to resolve this error? Or shall I make another pr correcting this?

**Comment by rahulsain3000** [comment]
@VenkatVuddagiri I already corrected the code on your side and merged successfully

**Comment by VenkatVuddagiri** [comment]
Sorry for my mistake bro. I'll make sure that it will not happen again.

**Pull request merged**
