### PR TITLE
added day_2

### PR DESCRIPTION
**Pull request by GauravPoosarla**

### CODE REVIEW

**Comment by GauravPoosarla** [comment]
I was assigned for it, please accept it.

**Comment by rahulsain3000** [comment]
I recently checked and sorry to say but this file already exist.

**Comment by GauravPoosarla** [comment]
Atleast give me the label, don't merge it or else it will be counted as spam, you can give a label hacktoberfest-accepted, please

**Comment by rahulsain3000** [comment]
@GauravPoosarla Please read this:
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by rahulsain3000** [comment]
Please make a valid PR, cross check your code with this repo before making a PR

**Comment by GauravPoosarla** [comment]
ok sorry from next time i will check.

**Pull request closed without merging**
