### PR TITLE
New codes added

### PR DESCRIPTION
**Pull request by yash982000**

### CODE REVIEW

**Comment by yash982000** [comment]
@rahulsain3000  Merge this so that I can change the repo to latest changes.

**Comment by rahulsain3000** [comment]
Why are you changing the link though?

**Comment by yash982000** [comment]
@rahulsain3000  Which link?

**Comment by rahulsain3000** [comment]
`<a href="https://github.com/yash982000/Hackerrank_30daysOFcode"><strong>View the Repo</strong></a>`
the changes you made in this commit

**Comment by yash982000** [comment]
Ohh that is because I did it through different account by mistake. Fixed it. You can now merege. @rahulsain3000

**Comment by rahulsain3000** [comment]
@yash982000 But I see no changes in the code but still I merged it

**Comment by yash982000** [comment]
@rahulsain3000 That is because I did revert those wrong commits. And took the latest pull in my repo,

**Comment by rahulsain3000** [comment]
Ok, please update the readme file, some developer  don't make required change in readme  so add a point about `that or else their PR will be marked invalid`

**Comment by yash982000** [comment]
Okay, Also, I request you to add hactoberfest label to all those I merged as well as others as well since the rules re updated and it won't count in Hactoberfest otherwise.

**Comment by rahulsain3000** [comment]
@yash982000 can you send me the link of updated rules?

**Comment by rahulsain3000** [comment]
> @yash982000 can you send me the link of updated rules?

We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.

So those will still count as long as they are merged

**Comment by yash982000** [comment]
@rahulsain3000 https://github.com/rahulsain3000/Hackerrank_30daysOFcode/pull/322

**Comment by yash982000** [comment]
@rahulsain3000  Yes, those done earlier would be but after yesterday 5:30 pm IST, only those with labels of Hactoberfest and Hactoberfest accepted will be accepted. So, make sure you do that. Other things we will take care. As our repo is growing, we should be more professional now.

**Comment by yash982000** [comment]
@rahulsain3000  You must go through this thoroughly if you haven't.
[](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

image

**Comment by rahulsain3000** [comment]
> @rahulsain3000 Yes, those done earlier would be but after yesterday 5:30 pm IST, only those with labels of Hactoberfest and Hactoberfest accepted will be accepted. So, make sure you do that. Other things we will take care. As our repo is growing, we should be more professional now.

There is choice between merged OR labelled as hacktober-accepted

**Comment by yash982000** [comment]
@rahulsain3000 Main thing is that the repo should be hactoberfest itself, rest three things are in OR, but the former is compulsory.

**Comment by rahulsain3000** [comment]
I have labelled this repo as hacktoberfest in the topic section as shown by [them](https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-eligible-gif.gif)

**Comment by rahulsain3000** [comment]
@yash982000 Please don't make tension among the masses, I already read update in detail

**Comment by yash982000** [comment]
@rahulsain3000  The point is not about tension bro, we still have time and we are just making sure no mistake happens,

**Comment by rahulsain3000** [comment]
So, what do you want me to do now? @yash982000

**Comment by yash982000** [comment]
@rahulsain3000  Everything is fine now. But, we just need to define the time. We can't update our repos at every hour. We can say we will merge PR's every 6 hours so there is no conflict for other contributors.

**Comment by rahulsain3000** [comment]
Ok point noted can you make required changes? I am making you a collaborator

**Comment by yash982000** [comment]
Okay, I will do, But I won't be available the whole time so I am giving this idea to mention in this repo.

**Comment by rahulsain3000** [comment]
Dont worry about handling PR I will do that work and I am updating the readme file. All I am saying that please update your idea in readme file so that everyone could understand why their PR rejected

**Pull request merged**
