### PR TITLE
Added day 18 files for c programing stacks and qeues

### PR DESCRIPTION
**Pull request by saiharsha-22**
Solved Day 18 problem using c program. Stacks and queues. #263

### CODE REVIEW

**Comment by rahulsain3000** [comment]
Hey , but Hackkerrank don't support C in this problem

**Comment by saiharsha-22** [comment]
@rahulsain3000 Can I add other sorting algorithms in C, Day 20 because there is only bubble sort.

**Comment by rahulsain3000** [comment]
@saiharsha-22 You know JAVA?

**Comment by saiharsha-22** [comment]
@rahulsain3000 yes

**Comment by saiharsha-22** [comment]
@rahulsain3000 Should I do in Java?

**Comment by rahulsain3000** [comment]
@saaranshM you can add all the algorithms you can want to add in this [repo](https://github.com/rahulsain3000/Java_DSA)

**Comment by saiharsha-22** [comment]
@rahulsain3000 Thank you I will add new algorithms now

**Comment by saaranshM** [comment]
@rahulsain3000 I think u tagged the wrong person.

**Comment by rahulsain3000** [comment]
Sorry @saaranshM

**Pull request merged**
