### PR TITLE
added day5

### PR DESCRIPTION
**Pull request by SudiptaAChy**
added day5 and final version of readme.md

### CODE REVIEW

**Review by rahulsain3000 — CHANGES_REQUESTED** [review]
Please dont make any change of readme file because I have already taken care of it

**Comment by SudiptaAChy** [comment]
ok sorry 
so i only have to upload day5 file?

**Comment by rahulsain3000** [comment]
Yes @SudiptaAChy

**Comment by rahulsain3000** [comment]
and please add day 1 to 5 again .

**Comment by SudiptaAChy** [comment]
> and please add day 1 to 5 again .

done

**Review by rahulsain3000 — CHANGES_REQUESTED** [review]
Please copy readme file and paste it in your readme file to resolve conflict

**Comment by SudiptaAChy** [comment]
> Please copy readme file and paste it in your readme file to resolve conflict

sir copied and updated the readme file

**Pull request merged**
