### PR TITLE
Added day0.scala,  day1.scala, day2.scala, day3.scala

### PR DESCRIPTION
**Pull request by rishabhsudan**

### CODE REVIEW

**Comment by rahulsain3000** [comment]
Please resolve conflict so that I can merge your PR

**Comment by rishabhsudan** [comment]
@rahulsain3000  Merge request is resolved, kindly review

**Comment by rahulsain3000** [comment]
@rishabhsudan kindly add a column for scalar too

**Comment by rishabhsudan** [comment]
@rahulsain3000  the last column (Rust) in README.md is not proper..  Please check once.

**Comment by rahulsain3000** [comment]
@rishabhsudan Please wait before starting your work I am updating readme file currently

**Comment by rishabhsudan** [comment]
@rahulsain3000  Merge request is resolved, kindly review

**Comment by rahulsain3000** [comment]
> @rishabhsudan Please wait before starting your work I am updating readme file currently

Please wait iiam still fixing the issue #336

**Comment by rahulsain3000** [comment]
Please @rishabhsudan remove readme file, I am going to update readme file this time.

**Comment by rishabhsudan** [comment]
@rahulsain3000 removed.

**Comment by rahulsain3000** [comment]
@rishabhsudan Please resolve conflict

**Pull request closed without merging**
