### PR TITLE
Added Kotlin codes

### PR DESCRIPTION
**Pull request by sunny52525**
Added Kotlin

### CODE REVIEW

**Comment by rahulsain3000** [comment]
Please resolve conflicts

**Comment by sunny52525** [comment]
> Please resolve conflicts

done

**Comment by rahulsain3000** [comment]
Thanks @sunny52525 you were only one person who did the work in only 1 PR really appreciated.

**Comment by sunny52525** [comment]
your most welcome @rahulsain3000

**Pull request merged**
