### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Abhishek4uh**

### CODE REVIEW

**Comment by rahulsain3000** [comment]
Hi @Abhishek4uh please check that you're making changes in main readme file, please make a separate readme file in the folder
`30daysOFcode_C#`

**Comment by Abhishek4uh** [comment]
@rahulsain3000 I uploaded in a separate folder plz merge it. Thanks in Advance buddy!

**Comment by rahulsain3000** [comment]
Please add this readme file in the folder `Hackerrank_30daysOFcode/30daysOFcode_C#/`. Please don't make changes in main readme file `Hackerrank_30daysOFcode/`

**Comment by rahulsain3000** [comment]
@Abhishek4uh Update: please don't update these sentence in readme. I am closing this PR.
These sentence are not enough if comparing to pre existing readme file. Any updation is welcomed

**Pull request closed without merging**
